name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: withastro/action@v3
        with:
          path: ./dist
          deploy_key: ${{ secrets.DEPLOY_KEY }}